JuliaAI/MLJModels.jl

Manifest.toml
Project.toml
src/GLM.jl
test/GLM.jl
test/runtests.jl

Follow up from #2 cleaned up so that
**key**
* `predict(::OLS)` outputs a vector  of Normal
* `predict(::GLMCount)` outputs a  vector of Poisson
* `predict_mean` works as pointwise predict
**minor**
* I included changes to `*.toml` files, hopefully Travis will be ok with it (looks like it is, cool!)
* metadata fixed as per comments in #2 
* waiting for a pending discussion on binary outputs etc to implement `GLMBinary` etc (with Binomial/Probit and all that jazz)

GLMCount + probabilistic output

---

.travis.yml
Project.toml
src/MLJModels.jl
src/ScikitLearn.jl
test/ScikitLearn.jl
test/runtests.jl

Build is working (alongside the correct Python path with the change in Travis). 6 new models are implemented, but their traits still need correct defining.

Scikit learn

---

appveyor.yml

We should eventually also complement our travis testing with tests for windows, I think it needs to be activated on our repository first though.

[WIP] Windows Testing

---

appveyor.yml

Update the travis script to test on stable releases (1.0-1.1-1.2) + nightlies (1.3-1.4) allowing failures on the latter.

Update travis script

---

src/ScikitLearn/ScikitLearn.jl
src/ScikitLearn/ensemble.jl
src/ScikitLearn/gaussian-process.jl
src/ScikitLearn/linear-regressors.jl
test/ScikitLearn/ScikitLearn.jl
test/ScikitLearn/ensemble.jl
test/ScikitLearn/gaussian-process.jl
test/ScikitLearn/linear-regressors.jl

Small tweak in the @sk_model macro so that
1. in the multi-target case, `fit` expects a table for `y` and `predict` outputs a table
2. the name of the targets are passed
**note**: here, like in GLM, there is this slightly clunky way of passing additional informations along the "actual" fitresult which is used by the external package for the prediction; I believe it's fine for now but in some future it may be relevant to have `fit` return a 4-tuple with
```julia
return fitresult, aux_infos, cache, report
```
where `aux_infos` is possibly `nothing` or stuff like target names etc which would be passed along `fitresult` to `predict`. (we can discuss this some other time)

addresses issue #45

---

src/Clustering.jl
src/MLJModels.jl
src/MultivariateStats.jl
src/NearestNeighbors.jl
src/ScikitLearn/ScikitLearn.jl
src/parameters_utils.jl
test/NearestNeighbors.jl
test/parameters_utils.jl
test/runtests.jl

I believe this closes #53 
* addition of a `@mlj_model` macro, this is essentially similar to `@with_kw` except it includes the call to `clean!`, it's heavily inspired from the `@sk_model` macro though I tested it quite a bit and had to tweak a number of things to have it work robustly. 
* it also fixes a minor typo in the `sk_model` macro which could have caused issue (`ff` instead of `f`)
* this is now used in `Clustering`, `NearestNeighbors` and `MultivariateStats` (as per this PR)
**Note**: this is a very convenient way to quickly define the structs but it shouldn't be used everywhere. In particular it's currently not appropriate if the struct must be a parametric one. Also if the clean method is trivial, it's not necessary to use this. 
~~**Note**: currently passing apart from 1.0 …

Macro @mlj_model and tests

---

src/GLM.jl
src/MultivariateStats.jl
src/ScikitLearn/ScikitLearn.jl
src/builtins/Transformers.jl
test/ScikitLearn/linear-regressors.jl
test/Transformers.jl

this is a simple fix which I'll merge assuming all tests pass (no reason they wouldn't). 
Tables is already a dependency anyway so it really only avoids unnecessary computations. Later on we may rever this if we do want to access the extra field provided by MLJBase in the `fit` mechanism, that will be easy to revert.

using Tables.schema instead of MLJBase.schema when only needing names

---

Project.toml
src/DecisionTree.jl
test/runtests.jl

- (**Bug fix**) Address a class relabelling issue in DecisionTreeClassifier ([MLJ #319](https://github.com/alan-turing-institute/MLJ.jl/issues/319#issuecomment-549797570))

Fix class muddling in DecisionTreeClassifier

---

Project.toml

This is hack until we figure out why Compat 3.0 is breaking testing of LIBSVM and NaiveBayes and what to do about it.

add Compat so as to pin it to version 2.0

---

Project.toml
src/GLM.jl
src/ScikitLearn/ensemble.jl
test/ScikitLearn/ensemble.jl

* addresses #154 (randomforest* input scitype) + a fix for LinearRegressor in GLM

Small fixes [failing due to LIBSVM compat bound]

---

src/MultivariateStats.jl

Reset `regcoef` parameter in `LDA` and `BayesianLDA` models to a default value of `1e-6`. see: #181 
Also converted the `regcoef` type from `Real` which is used in the model struct to `Float64` used by the internal `MS.fit` method.

Reset regcoef parameter

---

Project.toml
README.md
src/model_search.jl
src/registry/Metadata.toml
src/registry/Models.toml
src/registry/Project.toml
src/registry/src/Registry.jl
src/registry/src/check_registry.jl
test/DecisionTree.jl

(**enhancement**) Add the boosted tree models from the pure-julia package [EvoTrees.jl](https://github.com/Evovest/EvoTrees.jl): `EvoTreeRegressor`, `EvoTreeGaussian`, `EvoTreeCount` and `EvoTreeClassifier` ([MLJ #122](https://github.com/alan-turing-institute/MLJ.jl/issues/122))

Add EvoTrees. For 0.8.1 release

---

Project.toml

This is a simple update of the Project.toml to be compatible with Tables 1.0 (as well as 0.2). This was tested locally with a similar change made to MLJBase.
It can be merged after https://github.com/alan-turing-institute/MLJBase.jl/pull/204 has been merged and released.
**Note**: also a bump in patch number.

compatible with tablesv1

---

src/builtins/Transformers.jl
test/builtins/Transformers.jl

`features` field is now accepting callable that returns Bool. That is, if `features(ftr)`, where `ftr` is a feature, returns true `ftr` is standardized.
Added `Bool` fields:
* `ignore` - if true, specified or evaluated features from `features` field are ignored.
* `ordered_factor` - if true, also standardizes `OrderedFactor` type
* `count` - if true, also standardizes `Count` type

Add fields in Standardizer, support callable in features field

---

Project.toml
src/ScikitLearn/ensemble.jl

#160 
Also remove `presort` hyperparameter in scikit-learn ensemble models to eliminate depreciation warnings.

Remove Compat.jl as explicit dependency

---

Project.toml
src/builtins/Transformers.jl
test/builtins/Transformers.jl

Fix a bug in `OneHotEncoder`: If `ordered_factor=false` any `OrderedFactor` column is being changed from a  `CategoricalVector` to a `Vector` of categorical elements, instead of being left-alone (which was changing the scitype ).

For a 0.9.5 release

---

src/model_search.jl
test/model_search.jl

add `models(regex::Regex)` method, which would enable us to find models easily.
EDIT: I expands method signature to `needle::Union{AbstractString,Regex}`

add `models(regex::Regex)` method

---

src/loading.jl

imho generals users should be able to load a model if s/he added MLJ.jl and each model provider package in their environment, and those helper packages like MLJModels.jl is better to be implicitly loaded rather than requires users to add it in their environment.
This PR should be totally backward compatible though.
fixes #248

don't require user's project explicitly list MLJModels

---

Project.toml

The last minor release 0.9.13 was actually breaking because of a subtle change in the way packages are loaded (to allow glue code and model algortihms to live in different packages). 
We should probably void the 0.9.13 release after this one.

For 0.10.0 release

---

Project.toml
src/loading.jl
test/loading.jl

Context: #242
New behaviour: 
- No error thrown if you try to load a model with a name clashing with an existing one. Rather the new model type is bound to a different name which is auto-generated by default (eg, `RidgeRegressor2`) with a warning issued, or bound to a name specified by a key-word argument `name=...`. 
- Previously only `@load` returned a default instance of the model; now `load` also does this. 
New doc-strings:
---
@load name pkg=nothing verbosity=0 name=nothing
Load the model implementation code for the model named in the first
argument into the calling module, specfying `pkg` in the case of
duplicate names. Return a model instance with default
hyper-parameters.
To bind the new model type to a name different from the first
argument, specify `name=...`.
@load …

Allow @load/load to import two models with same name from different packages

---

src/MultivariateStats.jl

This addresses https://github.com/alan-turing-institute/MLJBase.jl/issues/372 in a special case.

In PCA models, change maxoutdim default from nothing to 0

---

src/builtins/Transformers.jl

This PR
1. Makes `FillImputer` and `UnivariateFillImputer` models slightly more efficient
2. Add an error msg when applying `UnivariateFillImputer` to a  column `v` of `scitype` `AbstractVector{Union{Missing, <:Finite}}` if  the column doesn't contain the same levels as that of the categorical value `imputer` to be imputed. (i.e `all( in( levels(filler) ), levels(v) ) == true`). This implies that transforming a column of `elscitype`  `Union{Missing, OrderedFactor{N}` would always give a column of  `elscitype`  `OrderedFactor{N}`and transforming a column of `elscitype`  `Union{Missing, Multiclass{N}` would always give a column of  `elscitype`  `Multiclass{N}`.
3. The user can now specify the categorical value `filler` which is to be imputed in a column `v` of `scitype` …

improvements to  `FillImputer` and `UnivariateFillImputer` unsupervised models

---

Project.toml
src/MLJModels.jl
test/loading.jl
test/runtests.jl

**edited** 
The models from `GaussianProcesses` were never properly interfaced (and hence never added to the registry).We still have it in [extras], which is leading to package conflict headaches in CI.
So this PR removes GPs. The unfinished glue code is not removed, but the corresponding `include` has been removed.
It also removes testing for NaiveBayes, which has been leading to persistent CI headaches. The NaiveBayes glue code will be moved to a separate pkg [shortly](https://github.com/alan-turing-institute/MLJNaiveBayesInterface.jl), so no big deal.

Remove GaussianProcesses; Remove NaiveBayes testing

---

src/DecisionTree.jl

Fix typo: min number... instead of max number... for RandomForestRegressor
and RandomForestClassifier

Fix typo in docstrings of RandomForest{Regressor,Classifier}

---

src/MLJModels.jl
src/builtins/ThresholdPredictors.jl
test/builtins/ThresholdPredictors.jl
test/runtests.jl

Following discussion with @vollmersj on slack, this PR adds `BinaryThresholdPredictor` model. Which is essentially a model wrapping a `Binary` `Probabilistic` classifier and predicts a `Deterministic` response from the `AbstractArray{<:UnivariateFinite, 1}` predictions made from the wrapped model using a specified `threshold`.
This much like MLR's [tuneThreshold](https://mlr.mlr-org.com/reference/tuneThreshold.html) allows users to tune probability threshold by wrapping the `BinaryThresholdPredictor` model in a `TunedModel` wrapper.

Add BinaryThresholdPredictor model

---

src/MLJModels.jl
src/loading.jl
test/loading.jl

Addresses https://github.com/alan-turing-institute/MLJ.jl/issues/693 . 
- The intended behaviour of `@load` is not changed by this PR with this exception: By default `verbosity=1`, so that newcomers understand what the macros is doing. I think this has been a source of confusion a number of times.
```julia
julia> @load AdaBoostStumpClassifier
[ Info: For silent loading, specify `verbosity=0`. 
import MLJDecisionTreeInterface ✔
const AdaBoostStumpClassifier = MLJDecisionTreeInterface.AdaBoostStumpClassifier ✔
AdaBoostStumpClassifier(
n_iter = 10,
pdf_smoothing = 0.0) @036
```
- to load code without returning an instance of the new model type, there is a new macro `@loadcode`
- Support for the `load` function is removed.  Instead, for explicit importing of model types without a macro, the …

Refactor of @load

---

src/loading.jl
test/loading.jl

Fixes https://github.com/alan-turing-institute/MLJ.jl/issues/715
This pull request adds the optional `scope` keyword argument to the `@load` macro. The default value is `scope=:global`.
If the user sets `scope=:local`, we omit the `const` keyword. This allows users to use `@load` in local scope, where the `const` keyword is not allowed.
Before this PR:
```julia
julia> using MLJModels
julia> using Test
julia> @testset begin
@load DecisionTreeClassifier
end
[ Info: For silent loading, specify `verbosity=0`.
ERROR: syntax: unsupported `const` declaration on local variable around ~/.julia/dev/MLJModels.jl/src/loading.jl:82
Stacktrace:
[1] top-level scope
@ REPL[3]:1
```
After this PR:
```julia
julia> using MLJModels
julia> using Test
julia> @testset begin
@load DecisionTreeClassifier …
```

Add the optional `scope` keyword argument to the `@load` macro

---

Project.toml
src/loading.jl
test/loading.jl

This pull request adds the optional `install_pkgs` keyword argument to the `@load` macro.
If `install_pkgs` is `true`, then any necessary packages will automatically be installed.
The default value is `install_pkgs=false`.
Example usage:
```julia
julia> using MLJModels
julia> @load NeuralNetworkClassifier install_pkgs=true
```
@juliohm has brought up that installing all of the necessary packages is one of the pain points for Julia beginners when they first start out using MLJ.
Therefore, we can tell these beginner users to use `install_pkgs=true`, and then the necessary packages will automatically be installed for them.

Add the optional `install_pkgs` keyword argument to the `@load` macro

---

src/builtins/Transformers.jl
test/builtins/Transformers.jl

This PR tries to add a check for category level mismatch in OneHotEncoder.
As pointed out in #306, a transform function for OneHotEncoder returns wrong values when the transforming features have different category levels from fitting time.
This PR checks whether each transforming feature has the same category levels as the fitted version in the transform function and throws an exception when a mismatch is detected.
1. Add a dictionary into the OneHotEncoderResult struct and logic to store original category levels in it.
2. Add a check whether transforming features have the same levels as the stored levels.
3. Add a test case to confirm that an exception is thrown if a mismatch is detected.
4. Add a test case for the `ignore` option of OneHotEncoder because I found it missing in the …

Check onehotencoding category level

---

README.md
src/MLJModels.jl
src/model_search.jl
src/registry/Metadata.toml
src/registry/Models.toml
src/registry/Project.toml
src/registry/src/Registry.jl
test/model_search.jl

Adds these models:
```julia
julia> models("BetaML")
7-element Array{NamedTuple{(:name, :package_name, :is_supervised, :docstring, :hyperparameter_ranges, :hyperparameter_types, :hyperparameters, :implemented_methods, :is_pure_julia, :is_wrapper, :iteration_parameter, :load_path, :package_license, :package_url, :package_uuid, :prediction_type, :supports_class_weights, :supports_online, :supports_weights, :input_scitype, :target_scitype, :output_scitype),T} where T<:Tuple,1}:
(name = DecisionTreeClassifier, package_name = BetaML, ... )    
(name = DecisionTreeRegressor, package_name = BetaML, ... )     
(name = KernelPerceptronClassifier, package_name = BetaML, ... )
(name = PegasosClassifier, package_name = BetaML, ... )         
(name = PerceptronClassifier, package_name = BetaML, ... ) …
```

Add BetaML to registry

---

Project.toml
src/builtins/Transformers.jl
test/builtins/Transformers.jl

Replaces them with `CategoricalArrrays.DataAPI.unwrap`

Fix get depwarnings for CategoricalArrays.get

---

src/builtins/ThresholdPredictors.jl

Remove deprecation warnings for using `wrapped_model=...` instead of `model=...`

---

src/model_search.jl

Remove a redundant line of code (missed in a previous refactor?).
May improve the speed of `info(SomeModelType)`.

Remove redundant line of code

---

src/builtins/ThresholdPredictors.jl

Sometimes a composite type (eg, `Pipeline`) is not able to infer the `target_scitype`, which falls back to `Unknown`. It is consistent with MLJBase logic to simply drop the type check in that case.

Relax target scitype check for BinaryThresholdPredictor to allow `Unknown`

---

src/builtins/ThresholdPredictors.jl
src/utilities.jl
test/builtins/ThresholdPredictors.jl

This PR cleans up the trait declarations for `BinaryThresholdPredictor`. In particular:
- `iteration_parameter` trait inherits from atomic model: If, say, `:n` is the atomic value, then the wrapper gets the value `:(model.n)`. Previously, this returned `:unknown` always.
- `supports_training_losses` trait now inherits from atomic model. Previously returned `false` always.
- `training_losses(model, report)` accessor function now inherits from atomic model. Previously returned `nothing` always.
These improvements help `BinaryThresholdPredictor` play better with `IteratedModel`.

Improve inheritance for `BinaryThresholdPredictor` from atomic model

---

src/builtins/Transformers.jl
test/builtins/Transformers.jl

The behaviour is as follows:
```julia
julia> X = (name = categorical(["a", "b", "c", "a", "b", missing]),)
(name = Union{Missing, CategoricalArrays.CategoricalValue{String, UInt32}}["a", "b", "c", "a", "b", missing],)
julia> mach = machine(OneHotEncoder(), X)
Machine{OneHotEncoder,…} trained 0 times; caches data
model: OneHotEncoder
args: 
1:  Source @492 ⏎ `Table{AbstractVector{Union{Missing, Multiclass{3}}}}`
julia> fit!(mach)
[ Info: Training Machine{OneHotEncoder,…}.
[ Info: Spawning 3 sub-features to one-hot encode feature :name.
Machine{OneHotEncoder,…} trained 1 time; caches data
model: OneHotEncoder
args: 
1:  Source @492 ⏎ `Table{AbstractVector{Union{Missing, Multiclass{3}}}}`
julia> transform(mach)
(name__a = Union{Missing, Float64}[1.0, 0.0, 0.0, 1.0, 0.0, missing],
name__b = …
```

Add missing value propagation to OneHotEncoder

---

.github/workflows/ci.yml
Project.toml
src/MLJModels.jl
src/builtins/ThresholdPredictors.jl
test/builtins/ThresholdPredictors.jl

fixes #440 
```julia
julia> using MLJBase, MLJModels, EvoTrees
julia> threshold_classifier = BinaryThresholdPredictor(EvoTreeClassifier())
BinaryThresholdPredictor(
model = EvoTreeClassifier(
loss = EvoTrees.Softmax(),
nrounds = 10,
λ = 0.0,
γ = 0.0,
η = 0.1,
max_depth = 5,
min_weight = 1.0,
rowsample = 1.0,
colsample = 1.0,
nbins = 64,
α = 0.5,
metric = :mlogloss,
rng = Random.MersenneTwister(123),
device = "cpu"),
threshold = 0.5)
julia> X = MLJBase.table(rand(10, 10));
julia> y = categorical([2, 1, 1, 2, 1, 1, 2, 1, 1, 2], ordered=true);
julia> mach = machine(threshold_classifier, X, y) |> fit!
[ Info: Training Machine{BinaryThresholdPredictor{EvoTreeClassifier{Float64,…}},…}.
Machine{BinaryThresholdPredictor{EvoTreeClassifier{Float64,…}},…} trained 1 time; caches data
model: …
```

fix bug in data front-end issue#440

---

src/model_search.jl
test/model_search.jl

See https://github.com/alan-turing-institute/MLJ.jl/issues/937 for motivation.

`matching(X, y)` should print a warning if `y` is a table and `y` only has one column

---

src/builtins/ThresholdPredictors.jl
test/builtins/ThresholdPredictors.jl

To resolve #486.
Also adds a docstring to resolve https://github.com/alan-turing-institute/MLJ.jl/issues/973.

Catch unsupported model types in `BinaryThresholdPredictor`.

---

Project.toml
test/runtests.jl

The failure noted in #526 appears to be due to https://github.com/JuliaLang/Pkg.jl/issues/3628 . This PR adds a workaround to address the issue.

Add a workaround to fix CI failure for Julia 1.6

---

src/builtins/Transformers.jl

The meaning of `input_scitype` for `Static` models is not clear in the MLJ spec, a fact this is corrected [here](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/#Static-models-(models-that-do-not-generalize)). With this now clarified, the implementation for `InteractionTransformer` is not compliant and this PR fixes that.

Fix input_scitype for InteractionTransformer

---

.github/workflows/check_registry.yml

Disable redundant workaround in check_registry.yml

---

.github/workflows/ci.yml
Project.toml
src/builtins/ThresholdPredictors.jl
test/builtins/ThresholdPredictors.jl

This PR addresses part of https://github.com/alan-turing-institute/MLJ.jl/issues/1099

Overload `save` and `restore` to address serialization issue for `BinaryThresholdPredictor`

---

.github/workflows/ci.yml
src/builtins/Transformers.jl

Changes the float type of the fitresult of `Standardizer` to `AbstractFloat`. This means standardizers will no longer force floats to `Float64`.
I also removed the second definition of `fitresult_given_feature` - I think this must have been an oversight.

standardize AbstractFloats
