- Project.toml
- src/MLJModels.jl
- src/NaiveBayes.jl
- test/NaiveBayes.jl
An example usage is:
```
using MLJ
import MLJBase
@load GaussianNBClassifier
using NaiveBayes
using RDatasets
using StatsBase
using Random
iris = dataset("datasets", "iris")
X = convert(Array, iris[:, 1:4])
n, p = size(X)
y = [species for species in iris[:, 5]]
train_frac = 0.9
k = floor(Int, train_frac * n)
idxs = randperm(n)
train = idxs[1:k]
test = idxs[k+1:end];
m = GaussianNBClassifier(classes=unique(y), n=p)
r = MLJBase.fit(m, X[train ,:], y[train], 0)
MLJBase.predict(m, r[1], X[test, :])
```
To Do: 
1. Get this reviewed by @ablaom 
2. Add types to struct
3. Fix a few errors for MultinomialNB
> [WIP] Initial NaiveBayes classifier

- src/DecisionTree.jl
- test/DecisionTree.jl
The tests where taken from the DecisionTree test suite, they mightneed to be changed to fit our specification
> Decision tree

- src/MultivariateStats.jl
- test/MultivariateStats.jl
- test for PCA was re-written
- KernelPCA and ICA wrappers were re-written
- tests for KernelPCA and ICA were added
> Add KernelPCA and ICA

- Project.toml
- test/Clustering.jl
- test/DecisionTree.jl
- test/GLM.jl
- test/GaussianProcesses.jl
- test/LIBSVM.jl
- test/MultivariateStats.jl
- test/NaiveBayes.jl
- test/ScikitLearn.jl
- test/XGBoost.jl
- test/runtests.jl
This pull request makes the following changes:
1. Add CSV as a test dependency
This pull request is related to the changes in https://github.com/alan-turing-institute/MLJBase.jl/pull/24
> Add CSV as a test dependency

- src/Clustering.jl
- src/LIBSVM.jl
- src/ScikitLearn.jl
- test/Clustering.jl
closes https://github.com/alan-turing-institute/MLJ.jl/issues/202
> removing warnings etc, closes #202

- Project.toml
- src/Clustering.jl
- src/DecisionTree.jl
- src/GLM.jl
- src/GaussianProcesses.jl
- src/LIBSVM.jl
- src/MultivariateStats.jl
- src/NaiveBayes.jl
- src/ScikitLearn.jl
- src/XGBoost.jl
- test/Clustering.jl
- test/DecisionTree.jl
- test/GLM.jl
- test/GaussianProcesses.jl
- test/LIBSVM.jl
- test/MultivariateStats.jl
- test/NaiveBayes.jl
- test/ScikitLearn.jl
- test/XGBoost.jl
- test/runtests.jl
The changes are mostly concerned with adjusting model trait definitions, as described in [this MLJBase PR](https://github.com/alan-turing-institute/MLJBase.jl/pull/28)
> Update models to comply with MLJBase 0.4.0

- README.md
- src/GLM.jl
- test/GLM.jl
Poisson and NegativeBinomial
(and metadata fixes, the previous GLM PR had introduced some typos in the metadata)
I'll merge this assuming tests pass given that it's pretty much identical to the way the OLS is done.
> [glm] count regression

- Project.toml
- README.md
- src/Clustering.jl
- src/MLJModels.jl
- src/NearestNeighbors.jl
- src/metadata_utils.jl
- test/Clustering.jl
- test/NearestNeighbors.jl
- test/metadata.jl
- test/runtests.jl
And we should probably close the pr #9 
The test is a bit silly but it was mostly to check that dimensions are fine etc. 
Note the use of `permutedims` which will create a copy, transposes are not allowed to be passed to NNTree; there's an issue for this https://github.com/KristofferC/NearestNeighbors.jl/issues/82 where it's mentioned that materializing the transpose will lead to better performance.
> Interface with NearestNeighbors.jl

- Project.toml
- src/Clustering.jl
- src/MLJModels.jl
- src/NearestNeighbors.jl
- src/ScikitLearn/ScikitLearn.jl
- src/metadata_utils.jl
- src/parameters_utils.jl
- test/parameters_utils.jl
- test/runtests.jl
Reverts alan-turing-institute/MLJModels.jl#66
> Revert "Utilsmigration"

- Project.toml
- src/ScikitLearn/ScikitLearn.jl
- src/registry/Metadata.toml
- src/registry/Project.toml
- Workaround for #77 
- Resolution ofhttps://github.com/alan-turing-institute/MLJ.jl/issues/252
> Resolve load_path problem for ScikitLearn models

- src/GLM.jl
> replacing with_kw with with_kw_noshow 

- Project.toml
- README.md
- src/DecisionTree.jl
- src/GLM.jl
- src/MLJModels.jl
- src/NaiveBayes.jl
- src/ScikitLearn/ScikitLearn.jl
- test/DecisionTree.jl
- test/GLM.jl
> Towards 0.5.2

- src/MultivariateStats.jl
- test/MultivariateStats.jl
Implemented Bayesian Multiclass LDA.
> Implemented BayesianLDA model and added Tests

- src/NearestNeighbors.jl
- test/NearestNeighbors.jl
See #124 for context.
Not ready for merge yet as I'm still testing this.
This seems to "work"; however it'd be good to compare with sklearn or something similar to verify that the predictions are correct.
> Adding fit with weights

- src/MultivariateStats.jl
- test/MultivariateStats.jl
This PR implements
* `SubspaceLDA` model for High dimensional data
* `BayesianSubspaceLDA` model (Bayesian implementation)
* `transform` method for all LDA models
> Added Subspace LDA  models.

- src/DecisionTree.jl
Resolves https://github.com/alan-turing-institute/MLJ.jl/issues/347
> Add `print_tree` to report of DCC 

- src/XGBoost.jl
- test/XGBoost.jl
> Allow more general objective functions in XGBoostRegressor. Closes #96

- src/DecisionTree.jl
- test/DecisionTree.jl
> Allow DecisionTree to support ordinal features

- src/builtins/Transformers.jl
- test/builtins/Transformers.jl
Addresses first part of https://github.com/alan-turing-institute/MLJ.jl/issues/357
Addresses #95
> Transformer improvements

- README.md
- src/ScikitLearn/ScikitLearn.jl
- src/ScikitLearn/discriminant-analysis.jl
- src/ScikitLearn/ensemble.jl
- src/ScikitLearn/gaussian-process.jl
- src/ScikitLearn/linear-classifiers.jl
- src/ScikitLearn/linear-regressors.jl
- src/ScikitLearn/misc.jl
Cleans up the Readme significantly to add
- a step by step guide to write an interface with examples
- a step by step buide to registering a package
This should hopefully help package devs.
I'll merge this assuming tests pass, we can review it in more details later on.
> Readme: step-by-step guide for package devs

- src/Clustering.jl
- test/Clustering.jl
https://github.com/alan-turing-institute/MLJ.jl/issues/418
> cluster labels should be categorical elements

- src/ScikitLearn/ScikitLearn.jl
- src/ScikitLearn/clustering.jl
- src/ScikitLearn/discriminant-analysis.jl
- src/builtins/Transformers.jl
- test/ScikitLearn/ScikitLearn.jl
- test/ScikitLearn/clustering.jl
Added most clustering models from sklearn  apart from Bi and Co clustering which are a bit different. Overall there's 2 hyperparam that caused me trouble:
- pooling_func in featureagglom
- n_components in spectral clustering seems to not be supported
rest should behave the same way. I'll merge this with tests passing as it's independent code and do a minor release.
> Sklearn clustering

- Project.toml
- README.md
- src/ScikitLearn/ScikitLearn.jl
- src/ScikitLearn/clustering.jl
- src/ScikitLearn/discriminant-analysis.jl
- src/builtins/Transformers.jl
- test/ScikitLearn/ScikitLearn.jl
- test/ScikitLearn/clustering.jl
Main change: addition of sklearn clustering models, improvements of interface guidelines.
> Patch  release

- Project.toml
Requires 1.0 was a non breaking change, so it is fine to allow Requires 1.0.
> Allow Requires 1.0

- Project.toml
- src/model_search.jl
> For a 0.8.2 release

- Project.toml
- src/MLJModels.jl
- src/XGBoost.jl
- src/loading.jl
- src/model_search.jl
- src/registry/Metadata.toml
- src/registry/src/check_registry.jl
- test/ScikitLearn/clustering.jl
- test/runtests.jl
#202 
~~The source branch in this PR is not synchronised with a tagged release of `MLJModelInterface` or `MLJBase` but with the `early-march` branches of those repositories.~~
~~It is expected to fail on travis.~~
Before merging:
> For a 0.9.0 release

- Project.toml
Removed the [compat] entry but forgot to remove the from [deps].
> For a 0.9.2 release - take #2

- Project.toml
- test/Clustering.jl
- test/DecisionTree.jl
- test/GLM.jl
- test/GaussianProcesses.jl
- test/LIBSVM.jl
- test/MultivariateStats.jl
- test/NaiveBayes.jl
- test/ScikitLearn/ScikitLearn.jl
- test/ScikitLearn/svm.jl
- test/runtests.jl
> Remove all use of RDatasets 

- src/MLJModels.jl
- src/builtins/Transformers.jl
- test/builtins/Transformers.jl
- test/runtests.jl
> Continuous encoder

- Project.toml
- src/GLM.jl
- test/GLM.jl
Bug fixes:
- #235 
- https://github.com/alan-turing-institute/MLJ.jl/issues/498
> For a 0.9.7 release (bug fixes)

- src/LIBSVM.jl
- src/builtins/Transformers.jl
This closes issue #253.
This also addresses issue #241
> Add cache parameter and change default values for LIBSVM models

- src/DecisionTree.jl
> Change defaults of DecisionTree models to coincide with pkg 

- Project.toml
- src/builtins/Transformers.jl
- src/registry/Metadata.toml
- src/registry/src/check_registry.jl
- test/builtins/Transformers.jl
> let Standardizer do univariate standardization as well #281

- src/builtins/Transformers.jl
- test/builtins/Transformers.jl
- test/runtests.jl
> Inverse transform for standardizer 

- Project.toml
- src/builtins/Transformers.jl
- test/builtins/Transformers.jl
- test/runtests.jl
> For a 0.11.2 release

- Project.toml
- test/loading.jl
> Temporarily suspend some testing because of a test pkg conflict

- Project.toml
- src/MultivariateStats.jl
> For a 0.12.2 release

- Project.toml
> extend [compat] +Distributions = "^0.22,^0.23,^0.24"; bump version

- Project.toml
> For a 0.12.6 release

- Project.toml
- src/loading.jl
- test/loading.jl
> For a 0.13.2 release

- .github/workflows/ci.yml
- Project.toml
- src/metadata.jl
- src/model_search.jl
- test/metadata.jl
> Tweak behaviour of localmodeltypes to resolve #356

- .github/workflows/check_registry.yml
- README.md
- src/registry/Metadata.toml
- src/registry/src/Registry.jl
- src/registry/src/check_registry.jl
- test/info_dict.jl
> Add check_registry to CI (continued)

- .github/workflows/ci.yml
- Project.toml
- README.md
- src/MLJModels.jl
- src/registry/Metadata.toml
- src/registry/Models.toml
```
julia> models("BetaML")
11-element Array{NamedTuple{(:name, :package_name, :is_supervised, :docstring, :hyperparameter_ranges, :hyperparameter_types, :hyperparameters, :implemented_methods, :is_pure_julia, :is_wrapper, :iteration_parameter, :load_path, :package_license, :package_url, :package_uuid, :prediction_type, :supports_class_weights, :supports_online, :supports_training_losses, :supports_weights, :input_scitype, :target_scitype, :output_scitype),T} where T<:Tuple,1}:
(name = DecisionTreeClassifier, package_name = BetaML, ... )    
(name = DecisionTreeRegressor, package_name = BetaML, ... )     
(name = GMMClusterer, package_name = BetaML, ... )              
(name = KMeans, package_name = BetaML, ... )                    
(name = KMedoids, package_name = BetaML, ... ) …
```
> Add more BetaML models to the registry

- Project.toml
> Extend compat CategoricalArrays = "0.9, 0.10"; bump 0.15.4

- .github/workflows/ci.yml
- Project.toml
> for 0.15.4 release

- test/info_dict.jl
To resolve fails in other PR's
> Fix an invalid test

- src/builtins/Transformers.jl
- test/info_dict.jl
> Quiten `Standardizer`

- Project.toml
> For a 0.15.1 release

- src/MLJModels.jl
- src/builtins/Transformers.jl
https://github.com/alan-turing-institute/MLJ.jl/issues/901
> Add MLJ-compliant document strings to all transformers

- src/builtins/Transformers.jl
- test/builtins/Transformers.jl
Fix: https://github.com/JuliaAI/MLJModels.jl/issues/467
> fix one hot encoder when first value in column is missing

- .github/workflows/check_registry.yml
I adjusted the `test_registry.yml` to allow the `check_registry` ci run. Please make sure to remove such checks before merging this PR
> add hack to allow ci pass

- src/builtins/Transformers.jl
- test/builtins/Transformers.jl
> Improve fitted_params for Tranformers.jl

- src/registry/Metadata.toml
- src/registry/Models.toml
- src/registry/Project.toml
> Add the model from SelfOrganizingMaps.jl to the model registry

- src/builtins/Constant.jl
> fix dep warnings in ConstantClassifier and Regressor models

- src/builtins/Constant.jl
Reverts JuliaAI/MLJModels.jl#515
> Revert "For a 0.16.8 release"

- Project.toml
- src/builtins/Constant.jl
> For a 0.16.8 release

- Project.toml
- src/builtins/Constant.jl
> For 0.16.8 release

- Project.toml
- src/MLJModels.jl
> Remove `export FeatureSelector`, as moved to FeatureSelection.jl
